I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 308, in script
    "Я думаю о том, что Михаил называл меня "Лекси", и очень мило смеялся. Я думаю о том, что Михаил сказал мне, что я милый."
Exception: Say has image attributes ('Лекси',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 308, in script
    "Я думаю о том, что Михаил называл меня "Лекси", и очень мило смеялся. Я думаю о том, что Михаил сказал мне, что я милый."
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/exports.py", line 1491, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/defaultstore.py", line 419, in say
    who(what, *args, interact=interact, **kwargs)
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/character.py", line 1332, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/character.py", line 1151, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "/Users/asahium/Downloads/renpy-8.2.1-sdk/renpy/character.py", line 1077, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('Лекси',), but there's no image tag associated with the speaking character.

macOS-14.4.1-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
I am ill and you are my symptom 1.0
Tue Apr  2 20:11:58 2024
